### ISSUE TITLE
Working config stops after reboot

### ISSUE THREAD

**Issue by chrisriteco** [mtz8302/AOG_Dual_GPS#2]
Strange problem, I setup the hardware and make the config work with the webinterface. Turned the debug + ubx on and everything works ok. 

When I make a total reboot (ESP + 2x F9P) the configuration is not coming back functional and debug is off in the serial monitor.

First I was thinking of power problems,  but I found out, when I simple hit the button 'Apply and Save' on the webinterface within the GPIO section (without change anything) the setup is working again.

Hope this can fixed.

**Comment by mtz8302** [comment]
I made a complete rewrite of the web interface. Give a try on beta branch

**Comment by mtz8302** [comment]
is this problem solved for you?
