### ISSUE TITLE
Possibly wrong if stm logic

### ISSUE THREAD

**Issue by pawliczka** [mtz8302/AOG_Dual_GPS#6]
https://github.com/mtz8302/AOG_GPS_ESP32/blob/dca3f5ebf1023ed7a3645c8c8e246a321c71225a/AOG_GPS_ESP32/zAOG_Heading_and_Position_calc.ino#L295

Hello. Are you sure about this if stm? Shouldn't it be 
`if (abs(cosHeadVTG) > 0.98)`

**Comment by mtz8302** [comment]
You are right
THX
